[phases.setup]
nixPkgs = ["nodejs_20"] 

[phases.install]
cmds = ["npm ci"]  # Install dependencies

[phases.build]
cmds = ["npm run build"]  # Build the Next.js app

[start]
cmd = "npm run start"  # Start the app