name: Build and Deploy Next.js to GHCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug Secret
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo "SENTRY_AUTH_TOKEN is: $SENTRY_AUTH_TOKEN"
          if [ -z "$SENTRY_AUTH_TOKEN" ]; then
            echo "Token is empty or unset!"
            exit 1
          else
            echo "Token is set (length: ${#SENTRY_AUTH_TOKEN})"
          fi

      # Build and push Docker image with Nixpacks action
      - name: Build and push Docker image
        uses: iloveitaly/github-action-nixpacks@main
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          context: . # Path to your Next.js app (root by default)
          env: |
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SENTRY_PROJECT }}
          push: true # Push to registry
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          # Optional: Customize Nixpacks build args if needed
          nixpacks_args: "--name ${{ env.IMAGE_NAME }}"

      # Trigger Coolify deployment (optional webhook)
      - name: Trigger Coolify deployment
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
        if: success()
