name: Build and Deploy Next.js to GHCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Install Nixpacks CLI
      - name: Install Nixpacks
        run: curl -sSL https://nixpacks.com/install.sh | bash

      # Build and push Docker image with Nixpacks CLI
      - name: Build and push Docker image
        run: |
          nixpacks build . \
            --name ${{ env.IMAGE_NAME }} \
            --tag ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --push

      # Trigger Coolify deployment (optional webhook)
      - name: Trigger Coolify deployment
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
        if: success()
