on:
  push:
    branches:
      - main
jobs:
  check_todo:
    name: check for TODO and create issues
    runs-on: ubuntu-latest
    steps:
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
